import { useState } from "react";
import { Shield, Settings, Map, AlertTriangle } from "lucide-react";
import { RouteInput } from "./components/route-input";
import { SafetyPreferences, SafetyPrefs } from "./components/safety-preferences";
import { MapView } from "./components/map-view";
import { RouteComparison } from "./components/route-comparison";
import { RealTimeMonitor } from "./components/real-time-monitor";
import { SettingsPanel } from "./components/settings-panel";
import { RouteData } from "./components/route-card";
import { Card } from "./components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./components/ui/tabs";
import { Button } from "./components/ui/button";

// Mock route data generated by AI analysis
const generateMockRoutes = (preferences: SafetyPrefs): RouteData[] => {
  return [
    {
      id: 1,
      name: "Route A - Main Street",
      distance: "3.2 km",
      duration: "12 min",
      safetyScore: 92,
      factors: {
        lighting: 95,
        crowdDensity: 88,
        riskZones: 92,
        timeOfDay: 90,
      },
      recommendation: 'best',
    },
    {
      id: 2,
      name: "Route B - Park Avenue",
      distance: "2.8 km",
      duration: "10 min",
      safetyScore: 78,
      factors: {
        lighting: 75,
        crowdDensity: 82,
        riskZones: 80,
        timeOfDay: 75,
      },
      recommendation: 'fastest',
    },
    {
      id: 3,
      name: "Route C - Commercial District",
      distance: "3.5 km",
      duration: "14 min",
      safetyScore: 85,
      factors: {
        lighting: 90,
        crowdDensity: 85,
        riskZones: 82,
        timeOfDay: 83,
      },
      recommendation: 'balanced',
    },
  ];
};

export default function App() {
  const [source, setSource] = useState("");
  const [destination, setDestination] = useState("");
  const [showRoutes, setShowRoutes] = useState(false);
  const [routes, setRoutes] = useState<RouteData[]>([]);
  const [selectedRoute, setSelectedRoute] = useState<number | undefined>();
  const [isTracking, setIsTracking] = useState(false);
  const [activeTab, setActiveTab] = useState("plan");
  
  const [preferences, setPreferences] = useState<SafetyPrefs>({
    prioritizeSafety: 75,
    avoidDarkAreas: true,
    preferCrowdedAreas: true,
    avoidHighRiskZones: true,
  });

  const handleFindRoutes = () => {
    const generatedRoutes = generateMockRoutes(preferences);
    setRoutes(generatedRoutes);
    setShowRoutes(true);
    setActiveTab("routes");
  };

  const handleStartNavigation = () => {
    setIsTracking(true);
    setActiveTab("monitor");
  };

  const handleStopTracking = () => {
    setIsTracking(false);
    setActiveTab("plan");
  };

  return (
    <div className="size-full bg-gray-50 flex flex-col">
      {/* Header */}
      <header className="bg-white border-b border-gray-200 px-4 py-4 md:px-6">
        <div className="flex items-center justify-between max-w-7xl mx-auto">
          <div className="flex items-center gap-3">
            <div className="bg-gradient-to-br from-purple-500 to-pink-500 p-2 rounded-lg">
              <Shield className="size-6 text-white" />
            </div>
            <div>
              <h1 className="text-lg md:text-xl">Guardian Route</h1>
              <p className="text-sm text-gray-500">AI-Powered Safety Navigation for Women</p>
            </div>
          </div>
          <Button
            variant="outline"
            size="icon"
            onClick={() => setActiveTab("settings")}
          >
            <Settings className="size-5" />
          </Button>
        </div>
      </header>

      {/* Main Content */}
      <div className="flex-1 overflow-hidden">
        <Tabs value={activeTab} onValueChange={setActiveTab} className="h-full flex flex-col">
          <div className="border-b border-gray-200 bg-white px-4 md:px-6">
            <div className="max-w-7xl mx-auto">
              <TabsList className="w-full md:w-auto">
                <TabsTrigger value="plan" className="flex-1 md:flex-none">
                  <Map className="size-4 mr-2" />
                  Plan Route
                </TabsTrigger>
                <TabsTrigger value="routes" className="flex-1 md:flex-none" disabled={!showRoutes}>
                  <Shield className="size-4 mr-2" />
                  Routes
                </TabsTrigger>
                <TabsTrigger value="monitor" className="flex-1 md:flex-none" disabled={!isTracking}>
                  <AlertTriangle className="size-4 mr-2" />
                  Monitor
                </TabsTrigger>
                <TabsTrigger value="settings" className="flex-1 md:flex-none">
                  <Settings className="size-4 mr-2" />
                  Settings
                </TabsTrigger>
              </TabsList>
            </div>
          </div>

          <div className="flex-1 overflow-auto">
            <div className="max-w-7xl mx-auto p-4 md:p-6 h-full">
              <TabsContent value="plan" className="mt-0 h-full">
                <div className="grid md:grid-cols-3 gap-6 h-full">
                  {/* Left Panel - Input */}
                  <div className="md:col-span-1 space-y-6">
                    <Card className="p-6">
                      <RouteInput
                        source={source}
                        destination={destination}
                        onSourceChange={setSource}
                        onDestinationChange={setDestination}
                        onFindRoutes={handleFindRoutes}
                      />
                    </Card>
                    
                    <Card className="p-6">
                      <SafetyPreferences
                        preferences={preferences}
                        onPreferencesChange={setPreferences}
                      />
                    </Card>
                  </div>

                  {/* Right Panel - Map */}
                  <div className="md:col-span-2 h-[400px] md:h-full">
                    <MapView selectedRoute={selectedRoute} />
                  </div>
                </div>
              </TabsContent>

              <TabsContent value="routes" className="mt-0 h-full">
                <RouteComparison
                  routes={routes}
                  selectedRoute={selectedRoute}
                  onSelectRoute={setSelectedRoute}
                  onStartNavigation={handleStartNavigation}
                />
              </TabsContent>

              <TabsContent value="monitor" className="mt-0 h-full">
                <RealTimeMonitor 
                  selectedRoute={selectedRoute}
                  onStopTracking={handleStopTracking}
                />
              </TabsContent>

              <TabsContent value="settings" className="mt-0 h-full">
                <SettingsPanel />
              </TabsContent>
            </div>
          </div>
        </Tabs>
      </div>
    </div>
  );
}